#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"
#import "ASPCalendarItem.h"


@protocol ASPCalendarItems
@end

@interface ASPCalendarItems : ASPObject


@property(nonatomic) NSArray<ASPCalendarItem>* list;

@property(nonatomic) ASPLink* link;

@end
