#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"


@protocol ASPCalendarItem
@end

@interface ASPCalendarItem : ASPObject


@property(nonatomic) ASPLink* link;

@property(nonatomic) NSNumber* uid;

@property(nonatomic) NSString* name;

@end
