#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPWorkingTime.h"


@protocol ASPCalendarException
@end

@interface ASPCalendarException : ASPObject


@property(nonatomic) NSNumber* enteredByOccurrences;

@property(nonatomic) NSDate* fromDate;

@property(nonatomic) NSDate* toDate;

@property(nonatomic) NSNumber* occurrences;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* type;

@property(nonatomic) NSNumber* period;

@property(nonatomic) NSString* monthItem;

@property(nonatomic) NSString* monthPosition;

@property(nonatomic) NSString* month;

@property(nonatomic) NSNumber* monthDay;

@property(nonatomic) NSNumber* dayWorking;

@property(nonatomic) NSArray<ASPWorkingTime>* workingTimes;

@property(nonatomic) NSArray* /* NSString */ daysOfWeek;

@end
