#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPDocumentProperty.h"


@protocol ASPDocumentPropertyResponse
@end

@interface ASPDocumentPropertyResponse : ASPObject


@property(nonatomic) ASPDocumentProperty* _property;

@property(nonatomic) NSString* code;

@property(nonatomic) NSString* status;

@end
