#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"
#import "ASPExtendedAttributeItem.h"


@protocol ASPExtendedAttributeItems
@end

@interface ASPExtendedAttributeItems : ASPObject


@property(nonatomic) NSArray<ASPExtendedAttributeItem>* list;

@property(nonatomic) ASPLink* link;

@end
