#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPOutlineValue.h"
#import "ASPOutlineMask.h"


@protocol ASPOutlineCodeDefinition
@end

@interface ASPOutlineCodeDefinition : ASPObject


@property(nonatomic) NSString* guid;

@property(nonatomic) NSString* fieldId;

@property(nonatomic) NSString* fieldName;

@property(nonatomic) NSString* alias;

@property(nonatomic) NSString* phoneticAlias;

@property(nonatomic) NSArray<ASPOutlineValue>* values;

@property(nonatomic) NSNumber* enterprise;

@property(nonatomic) NSNumber* enterpriseOutlineCodeAlias;

@property(nonatomic) NSNumber* resourceSubstitutionEnabled;

@property(nonatomic) NSNumber* leafOnly;

@property(nonatomic) NSNumber* allLevelsRequired;

@property(nonatomic) NSNumber* onlyTableValuesAllowed;

@property(nonatomic) NSArray<ASPOutlineMask>* masks;

@property(nonatomic) NSNumber* showIndent;

@end
