#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPOutlineCode
@end

@interface ASPOutlineCode : ASPObject


@property(nonatomic) NSString* fieldId;

@property(nonatomic) NSNumber* valueId;

@property(nonatomic) NSString* valueGuid;

@end
