#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPOutlineCodeItem.h"
#import "ASPLink.h"


@protocol ASPOutlineCodeItems
@end

@interface ASPOutlineCodeItems : ASPObject


@property(nonatomic) NSArray<ASPOutlineCodeItem>* list;

@property(nonatomic) ASPLink* link;

@end
