#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPExtendedAttribute.h"
#import "ASPOutlineCode.h"


@protocol ASPResource
@end

@interface ASPResource : ASPObject


@property(nonatomic) NSString* name;

@property(nonatomic) NSNumber* uid;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* type;

@property(nonatomic) NSNumber* isNull;

@property(nonatomic) NSString* initials;

@property(nonatomic) NSString* phonetics;

@property(nonatomic) NSString* ntAccount;

@property(nonatomic) NSString* materialLabel;

@property(nonatomic) NSString* code;

@property(nonatomic) NSString* group;

@property(nonatomic) NSString* emailAddress;

@property(nonatomic) NSString* hyperlink;

@property(nonatomic) NSString* hyperlinkAddress;

@property(nonatomic) NSString* hyperlinkSubAddress;

@property(nonatomic) NSNumber* maxUnits;

@property(nonatomic) NSNumber* peakUnits;

@property(nonatomic) NSNumber* overAllocated;

@property(nonatomic) NSDate* availableFrom;

@property(nonatomic) NSDate* availableTo;

@property(nonatomic) NSDate* start;

@property(nonatomic) NSDate* finish;

@property(nonatomic) NSNumber* canLevel;

@property(nonatomic) NSString* accrueAt;

@property(nonatomic) NSString* work;

@property(nonatomic) NSString* regularWork;

@property(nonatomic) NSString* overtimeWork;

@property(nonatomic) NSString* actualWork;

@property(nonatomic) NSString* remainingWork;

@property(nonatomic) NSString* actualOvertimeWork;

@property(nonatomic) NSString* remainingOvertimeWork;

@property(nonatomic) NSNumber* percentWorkComplete;

@property(nonatomic) NSNumber* standardRate;

@property(nonatomic) NSString* standardRateFormat;

@property(nonatomic) NSNumber* cost;

@property(nonatomic) NSString* overtimeRateFormat;

@property(nonatomic) NSNumber* overtimeCost;

@property(nonatomic) NSNumber* costPerUse;

@property(nonatomic) NSNumber* actualCost;

@property(nonatomic) NSNumber* actualOvertimeCost;

@property(nonatomic) NSNumber* remainingCost;

@property(nonatomic) NSNumber* remainingOvertimeCost;

@property(nonatomic) NSNumber* workVariance;

@property(nonatomic) NSNumber* costVariance;

@property(nonatomic) NSNumber* sv;

@property(nonatomic) NSNumber* cv;

@property(nonatomic) NSNumber* acwp;

@property(nonatomic) NSNumber* calendarUid;

@property(nonatomic) NSString* notesText;

@property(nonatomic) NSNumber* bcws;

@property(nonatomic) NSNumber* bcwp;

@property(nonatomic) NSNumber* isGeneric;

@property(nonatomic) NSNumber* isInactive;

@property(nonatomic) NSNumber* isEnterprise;

@property(nonatomic) NSString* bookingType;

@property(nonatomic) NSString* actualWorkProtected;

@property(nonatomic) NSString* actualOvertimeWorkProtected;

@property(nonatomic) NSString* activeDirectoryGuid;

@property(nonatomic) NSDate* creationDate;

@property(nonatomic) NSString* costCenter;

@property(nonatomic) NSNumber* isCostResource;

@property(nonatomic) NSNumber* teamAssignmentPool;

@property(nonatomic) NSString* assignmentOwner;

@property(nonatomic) NSString* assignmentOwnerGuid;

@property(nonatomic) NSNumber* isBudget;

@property(nonatomic) NSString* budgetWork;

@property(nonatomic) NSNumber* budgetCost;

@property(nonatomic) NSNumber* overtimeRate;

@property(nonatomic) NSString* baselineWork;

@property(nonatomic) NSNumber* baselineCost;

@property(nonatomic) NSNumber* baselineBcws;

@property(nonatomic) NSNumber* baselineBcwp;

@property(nonatomic) NSString* baseline1Work;

@property(nonatomic) NSNumber* baseline1Cost;

@property(nonatomic) NSNumber* baseline1Bcws;

@property(nonatomic) NSNumber* baseline1Bcwp;

@property(nonatomic) NSString* baseline2Work;

@property(nonatomic) NSNumber* baseline2Cost;

@property(nonatomic) NSNumber* baseline2Bcws;

@property(nonatomic) NSNumber* baseline2Bcwp;

@property(nonatomic) NSString* baseline3Work;

@property(nonatomic) NSNumber* baseline3Cost;

@property(nonatomic) NSNumber* baseline3Bcws;

@property(nonatomic) NSNumber* baseline3Bcwp;

@property(nonatomic) NSString* baseline4Work;

@property(nonatomic) NSNumber* baseline4Cost;

@property(nonatomic) NSNumber* baseline4Bcws;

@property(nonatomic) NSNumber* baseline4Bcwp;

@property(nonatomic) NSString* baseline5Work;

@property(nonatomic) NSNumber* baseline5Cost;

@property(nonatomic) NSNumber* baseline5Bcws;

@property(nonatomic) NSNumber* baseline5Bcwp;

@property(nonatomic) NSString* baseline6Work;

@property(nonatomic) NSNumber* baseline6Cost;

@property(nonatomic) NSNumber* baseline6Bcws;

@property(nonatomic) NSNumber* baseline6Bcwp;

@property(nonatomic) NSString* baseline7Work;

@property(nonatomic) NSNumber* baseline7Cost;

@property(nonatomic) NSNumber* baseline7Bcws;

@property(nonatomic) NSNumber* baseline7Bcwp;

@property(nonatomic) NSString* baseline8Work;

@property(nonatomic) NSNumber* baseline8Cost;

@property(nonatomic) NSNumber* baseline8Bcws;

@property(nonatomic) NSNumber* baseline8Bcwp;

@property(nonatomic) NSString* baseline9Work;

@property(nonatomic) NSNumber* baseline9Cost;

@property(nonatomic) NSNumber* baseline9Bcws;

@property(nonatomic) NSNumber* baseline9Bcwp;

@property(nonatomic) NSString* baseline10Work;

@property(nonatomic) NSNumber* baseline10Cost;

@property(nonatomic) NSNumber* baseline10Bcws;

@property(nonatomic) NSNumber* baseline10Bcwp;

@property(nonatomic) NSArray<ASPExtendedAttribute>* extendedAttributes;

@property(nonatomic) NSArray<ASPOutlineCode>* outlineCodes;

@end
