#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPResourceItems.h"


@protocol ASPResourceItemsResponse
@end

@interface ASPResourceItemsResponse : ASPObject


@property(nonatomic) ASPResourceItems* resources;

@property(nonatomic) NSString* code;

@property(nonatomic) NSString* status;

@end
