#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPExtendedAttribute.h"


@protocol ASPResourceAssignment
@end

@interface ASPResourceAssignment : ASPObject


@property(nonatomic) NSNumber* taskUid;

@property(nonatomic) NSNumber* resourceUid;

@property(nonatomic) NSNumber* uid;

@property(nonatomic) NSNumber* percentWorkComplete;

@property(nonatomic) NSNumber* actualCost;

@property(nonatomic) NSDate* actualFinish;

@property(nonatomic) NSNumber* actualOvertimeCost;

@property(nonatomic) NSString* actualOvertimeWork;

@property(nonatomic) NSDate* actualStart;

@property(nonatomic) NSString* actualWork;

@property(nonatomic) NSNumber* acwp;

@property(nonatomic) NSNumber* confirmed;

@property(nonatomic) NSNumber* cost;

@property(nonatomic) NSString* costRateTableType;

@property(nonatomic) NSNumber* costVariance;

@property(nonatomic) NSNumber* cv;

@property(nonatomic) NSNumber* delay;

@property(nonatomic) NSDate* finish;

@property(nonatomic) NSNumber* finishVariance;

@property(nonatomic) NSString* hyperlink;

@property(nonatomic) NSString* hyperlinkAddress;

@property(nonatomic) NSString* hyperlinkSubAddress;

@property(nonatomic) NSNumber* workVariance;

@property(nonatomic) NSNumber* hasFixedRateUnits;

@property(nonatomic) NSNumber* fixedMaterial;

@property(nonatomic) NSNumber* levelingDelay;

@property(nonatomic) NSString* levelingDelayFormat;

@property(nonatomic) NSNumber* linkedFields;

@property(nonatomic) NSNumber* milestone;

@property(nonatomic) NSString* notes;

@property(nonatomic) NSNumber* overallocated;

@property(nonatomic) NSNumber* overtimeCost;

@property(nonatomic) NSString* overtimeWork;

@property(nonatomic) NSNumber* peakUnits;

@property(nonatomic) NSString* regularWork;

@property(nonatomic) NSNumber* remainingCost;

@property(nonatomic) NSNumber* remainingOvertimeCost;

@property(nonatomic) NSString* remainingOvertimeWork;

@property(nonatomic) NSString* remainingWork;

@property(nonatomic) NSNumber* responsePending;

@property(nonatomic) NSDate* start;

@property(nonatomic) NSDate* stop;

@property(nonatomic) NSDate* resume;

@property(nonatomic) NSNumber* startVariance;

@property(nonatomic) NSNumber* summary;

@property(nonatomic) NSNumber* sv;

@property(nonatomic) NSNumber* units;

@property(nonatomic) NSNumber* updateNeeded;

@property(nonatomic) NSNumber* vac;

@property(nonatomic) NSString* work;

@property(nonatomic) NSString* workContour;

@property(nonatomic) NSNumber* bcws;

@property(nonatomic) NSNumber* bcwp;

@property(nonatomic) NSString* bookingType;

@property(nonatomic) NSString* actualWorkProtected;

@property(nonatomic) NSString* actualOvertimeWorkProtected;

@property(nonatomic) NSDate* creationDate;

@property(nonatomic) NSString* assnOwner;

@property(nonatomic) NSString* assnOwnerGuid;

@property(nonatomic) NSNumber* budgetCost;

@property(nonatomic) NSString* budgetWork;

@property(nonatomic) NSNumber* rateScale;

@property(nonatomic) NSDate* baselineStart;

@property(nonatomic) NSDate* baselineFinish;

@property(nonatomic) NSString* baselineWork;

@property(nonatomic) NSNumber* baselineCost;

@property(nonatomic) NSNumber* baselineBcws;

@property(nonatomic) NSNumber* baselineBcwp;

@property(nonatomic) NSDate* baseline1Start;

@property(nonatomic) NSDate* baseline1Finish;

@property(nonatomic) NSString* baseline1Work;

@property(nonatomic) NSNumber* baseline1Cost;

@property(nonatomic) NSNumber* baseline1Bcws;

@property(nonatomic) NSNumber* baseline1Bcwp;

@property(nonatomic) NSDate* baseline2Start;

@property(nonatomic) NSDate* baseline2Finish;

@property(nonatomic) NSString* baseline2Work;

@property(nonatomic) NSNumber* baseline2Cost;

@property(nonatomic) NSNumber* baseline2Bcws;

@property(nonatomic) NSNumber* baseline2Bcwp;

@property(nonatomic) NSDate* baseline3Start;

@property(nonatomic) NSDate* baseline3Finish;

@property(nonatomic) NSString* baseline3Work;

@property(nonatomic) NSNumber* baseline3Cost;

@property(nonatomic) NSNumber* baseline3Bcws;

@property(nonatomic) NSNumber* baseline3Bcwp;

@property(nonatomic) NSDate* baseline4Start;

@property(nonatomic) NSDate* baseline4Finish;

@property(nonatomic) NSString* baseline4Work;

@property(nonatomic) NSNumber* baseline4Cost;

@property(nonatomic) NSNumber* baseline4Bcws;

@property(nonatomic) NSNumber* baseline4Bcwp;

@property(nonatomic) NSDate* baseline5Start;

@property(nonatomic) NSDate* baseline5Finish;

@property(nonatomic) NSString* baseline5Work;

@property(nonatomic) NSNumber* baseline5Cost;

@property(nonatomic) NSNumber* baseline5Bcws;

@property(nonatomic) NSNumber* baseline5Bcwp;

@property(nonatomic) NSDate* baseline6Start;

@property(nonatomic) NSDate* baseline6Finish;

@property(nonatomic) NSString* baseline6Work;

@property(nonatomic) NSNumber* baseline6Cost;

@property(nonatomic) NSNumber* baseline6Bcws;

@property(nonatomic) NSNumber* baseline6Bcwp;

@property(nonatomic) NSDate* baseline7Start;

@property(nonatomic) NSDate* baseline7Finish;

@property(nonatomic) NSString* baseline7Work;

@property(nonatomic) NSNumber* baseline7Cost;

@property(nonatomic) NSNumber* baseline7Bcws;

@property(nonatomic) NSNumber* baseline7Bcwp;

@property(nonatomic) NSDate* baseline8Start;

@property(nonatomic) NSDate* baseline8Finish;

@property(nonatomic) NSString* baseline8Work;

@property(nonatomic) NSNumber* baseline8Cost;

@property(nonatomic) NSNumber* baseline8Bcws;

@property(nonatomic) NSNumber* baseline8Bcwp;

@property(nonatomic) NSDate* baseline9Start;

@property(nonatomic) NSDate* baseline9Finish;

@property(nonatomic) NSString* baseline9Work;

@property(nonatomic) NSNumber* baseline9Cost;

@property(nonatomic) NSNumber* baseline9Bcws;

@property(nonatomic) NSNumber* baseline9Bcwp;

@property(nonatomic) NSDate* baseline10Start;

@property(nonatomic) NSDate* baseline10Finish;

@property(nonatomic) NSString* baseline10Work;

@property(nonatomic) NSNumber* baseline10Cost;

@property(nonatomic) NSNumber* baseline10Bcws;

@property(nonatomic) NSNumber* baseline10Bcwp;

@property(nonatomic) NSArray<ASPExtendedAttribute>* extendedAttributes;

@end
