#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"
#import "ASPResourceItem.h"


@protocol ASPResourceItems
@end

@interface ASPResourceItems : ASPObject


@property(nonatomic) NSArray<ASPResourceItem>* resourceItem;

@property(nonatomic) ASPLink* link;

@end
