#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPExtendedAttribute.h"
#import "ASPOutlineCode.h"


@protocol ASPTask
@end

@interface ASPTask : ASPObject


@property(nonatomic) NSNumber* uid;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* duration;

@property(nonatomic) NSDate* start;

@property(nonatomic) NSDate* finish;

@property(nonatomic) NSNumber* percentComplete;

@property(nonatomic) NSNumber* percentWorkComplete;

@property(nonatomic) NSNumber* isActive;

@property(nonatomic) NSNumber* actualCost;

@property(nonatomic) NSString* actualDuration;

@property(nonatomic) NSDate* actualFinish;

@property(nonatomic) NSNumber* actualOvertimeCost;

@property(nonatomic) NSString* actualOvertimeWork;

@property(nonatomic) NSDate* actualStart;

@property(nonatomic) NSString* budgetWork;

@property(nonatomic) NSNumber* budgetCost;

@property(nonatomic) NSDate* constraintDate;

@property(nonatomic) NSString* constraintType;

@property(nonatomic) NSString* contact;

@property(nonatomic) NSNumber* cost;

@property(nonatomic) NSNumber* cv;

@property(nonatomic) NSDate* deadline;

@property(nonatomic) NSString* durationVariance;

@property(nonatomic) NSDate* earlyFinish;

@property(nonatomic) NSDate* earlyStart;

@property(nonatomic) NSNumber* isEffortDriven;

@property(nonatomic) NSNumber* isExternalTask;

@property(nonatomic) NSNumber* finishSlack;

@property(nonatomic) NSNumber* finishVariance;

@property(nonatomic) NSNumber* fixedCost;

@property(nonatomic) NSString* fixedCostAccrual;

@property(nonatomic) NSNumber* freeSlack;

@property(nonatomic) NSString* gUID;

@property(nonatomic) NSNumber* hideBar;

@property(nonatomic) NSNumber* ignoreResourceCalendar;

@property(nonatomic) NSDate* lateFinish;

@property(nonatomic) NSDate* lateStart;

@property(nonatomic) NSNumber* isLevelAssignments;

@property(nonatomic) NSNumber* canLevelingSplit;

@property(nonatomic) NSNumber* levelingDelay;

@property(nonatomic) NSNumber* isMarked;

@property(nonatomic) NSNumber* isMilestone;

@property(nonatomic) NSNumber* isCritical;

@property(nonatomic) NSNumber* isSubproject;

@property(nonatomic) NSNumber* isSubprojectReadOnly;

@property(nonatomic) NSString* subprojectName;

@property(nonatomic) NSNumber* isSummary;

@property(nonatomic) NSArray* /* NSNumber */ subtasksUids;

@property(nonatomic) NSNumber* outlineLevel;

@property(nonatomic) NSNumber* isOverAllocated;

@property(nonatomic) NSNumber* isEstimated;

@property(nonatomic) NSNumber* overtimeCost;

@property(nonatomic) NSString* overtimeWork;

@property(nonatomic) NSNumber* physicalPercentComplete;

@property(nonatomic) NSDate* preLeveledFinish;

@property(nonatomic) NSDate* preLeveledStart;

@property(nonatomic) NSNumber* isRecurring;

@property(nonatomic) NSString* regularWork;

@property(nonatomic) NSNumber* remainingCost;

@property(nonatomic) NSString* remainingDuration;

@property(nonatomic) NSNumber* remainingOvertimeCost;

@property(nonatomic) NSString* remainingOvertimeWork;

@property(nonatomic) NSString* remainingWork;

@property(nonatomic) NSDate* resume;

@property(nonatomic) NSNumber* isRollup;

@property(nonatomic) NSNumber* startSlack;

@property(nonatomic) NSNumber* startVariance;

@property(nonatomic) NSNumber* calendarUid;

@property(nonatomic) NSNumber* isManual;

@property(nonatomic) NSNumber* totalSlack;

@property(nonatomic) NSString* type;

@property(nonatomic) NSString* wbs;

@property(nonatomic) NSNumber* priority;

@property(nonatomic) NSString* work;

@property(nonatomic) NSNumber* workVariance;

@property(nonatomic) NSString* notesText;

@property(nonatomic) NSNumber* acwp;

@property(nonatomic) NSNumber* bcws;

@property(nonatomic) NSNumber* bcwp;

@property(nonatomic) NSString* levelingDelayFormat;

@property(nonatomic) NSString* predecessors;

@property(nonatomic) NSString* successors;

@property(nonatomic) NSDate* baselineStart;

@property(nonatomic) NSDate* baselineFinish;

@property(nonatomic) NSString* baselineDuration;

@property(nonatomic) NSNumber* baselineFixedCost;

@property(nonatomic) NSString* baselineDurationFormat;

@property(nonatomic) NSNumber* baselineEstimatedDuration;

@property(nonatomic) NSString* baselineWork;

@property(nonatomic) NSNumber* baselineCost;

@property(nonatomic) NSNumber* baselineBcws;

@property(nonatomic) NSNumber* baselineBcwp;

@property(nonatomic) NSDate* baseline1Start;

@property(nonatomic) NSDate* baseline1Finish;

@property(nonatomic) NSString* baseline1Duration;

@property(nonatomic) NSNumber* baseline1FixedCost;

@property(nonatomic) NSString* baseline1DurationFormat;

@property(nonatomic) NSNumber* baseline1EstimatedDuration;

@property(nonatomic) NSString* baseline1Work;

@property(nonatomic) NSNumber* baseline1Cost;

@property(nonatomic) NSNumber* baseline1Bcws;

@property(nonatomic) NSNumber* baseline1Bcwp;

@property(nonatomic) NSDate* baseline2Start;

@property(nonatomic) NSDate* baseline2Finish;

@property(nonatomic) NSString* baseline2Duration;

@property(nonatomic) NSNumber* baseline2FixedCost;

@property(nonatomic) NSString* baseline2DurationFormat;

@property(nonatomic) NSNumber* baseline2EstimatedDuration;

@property(nonatomic) NSString* baseline2Work;

@property(nonatomic) NSNumber* baseline2Cost;

@property(nonatomic) NSNumber* baseline2Bcws;

@property(nonatomic) NSNumber* baseline2Bcwp;

@property(nonatomic) NSDate* baseline3Start;

@property(nonatomic) NSDate* baseline3Finish;

@property(nonatomic) NSString* baseline3Duration;

@property(nonatomic) NSNumber* baseline3FixedCost;

@property(nonatomic) NSString* baseline3DurationFormat;

@property(nonatomic) NSNumber* baseline3EstimatedDuration;

@property(nonatomic) NSString* baseline3Work;

@property(nonatomic) NSNumber* baseline3Cost;

@property(nonatomic) NSNumber* baseline3Bcws;

@property(nonatomic) NSNumber* baseline3Bcwp;

@property(nonatomic) NSDate* baseline4Start;

@property(nonatomic) NSDate* baseline4Finish;

@property(nonatomic) NSString* baseline4Duration;

@property(nonatomic) NSNumber* baseline4FixedCost;

@property(nonatomic) NSString* baseline4DurationFormat;

@property(nonatomic) NSNumber* baseline4EstimatedDuration;

@property(nonatomic) NSString* baseline4Work;

@property(nonatomic) NSNumber* baseline4Cost;

@property(nonatomic) NSNumber* baseline4Bcws;

@property(nonatomic) NSNumber* baseline4Bcwp;

@property(nonatomic) NSDate* baseline5Start;

@property(nonatomic) NSDate* baseline5Finish;

@property(nonatomic) NSString* baseline5Duration;

@property(nonatomic) NSNumber* baseline5FixedCost;

@property(nonatomic) NSString* baseline5DurationFormat;

@property(nonatomic) NSNumber* baseline5EstimatedDuration;

@property(nonatomic) NSString* baseline5Work;

@property(nonatomic) NSNumber* baseline5Cost;

@property(nonatomic) NSNumber* baseline5Bcws;

@property(nonatomic) NSNumber* baseline5Bcwp;

@property(nonatomic) NSDate* baseline6Start;

@property(nonatomic) NSDate* baseline6Finish;

@property(nonatomic) NSString* baseline6Duration;

@property(nonatomic) NSNumber* baseline6FixedCost;

@property(nonatomic) NSString* baseline6DurationFormat;

@property(nonatomic) NSNumber* baseline6EstimatedDuration;

@property(nonatomic) NSString* baseline6Work;

@property(nonatomic) NSNumber* baseline6Cost;

@property(nonatomic) NSNumber* baseline6Bcws;

@property(nonatomic) NSNumber* baseline6Bcwp;

@property(nonatomic) NSDate* baseline7Start;

@property(nonatomic) NSDate* baseline7Finish;

@property(nonatomic) NSString* baseline7Duration;

@property(nonatomic) NSNumber* baseline7FixedCost;

@property(nonatomic) NSString* baseline7DurationFormat;

@property(nonatomic) NSNumber* baseline7EstimatedDuration;

@property(nonatomic) NSString* baseline7Work;

@property(nonatomic) NSNumber* baseline7Cost;

@property(nonatomic) NSNumber* baseline7Bcws;

@property(nonatomic) NSNumber* baseline7Bcwp;

@property(nonatomic) NSDate* baseline8Start;

@property(nonatomic) NSDate* baseline8Finish;

@property(nonatomic) NSString* baseline8Duration;

@property(nonatomic) NSNumber* baseline8FixedCost;

@property(nonatomic) NSString* baseline8DurationFormat;

@property(nonatomic) NSNumber* baseline8EstimatedDuration;

@property(nonatomic) NSString* baseline8Work;

@property(nonatomic) NSNumber* baseline8Cost;

@property(nonatomic) NSNumber* baseline8Bcws;

@property(nonatomic) NSNumber* baseline8Bcwp;

@property(nonatomic) NSDate* baseline9Start;

@property(nonatomic) NSDate* baseline9Finish;

@property(nonatomic) NSString* baseline9Duration;

@property(nonatomic) NSNumber* baseline9FixedCost;

@property(nonatomic) NSString* baseline9DurationFormat;

@property(nonatomic) NSNumber* baseline9EstimatedDuration;

@property(nonatomic) NSString* baseline9Work;

@property(nonatomic) NSNumber* baseline9Cost;

@property(nonatomic) NSNumber* baseline9Bcws;

@property(nonatomic) NSNumber* baseline9Bcwp;

@property(nonatomic) NSDate* baseline10Start;

@property(nonatomic) NSDate* baseline10Finish;

@property(nonatomic) NSString* baseline10Duration;

@property(nonatomic) NSNumber* baseline10FixedCost;

@property(nonatomic) NSString* baseline10DurationFormat;

@property(nonatomic) NSNumber* baselineEstimated10Duration;

@property(nonatomic) NSString* baseline10Work;

@property(nonatomic) NSNumber* baseline10Cost;

@property(nonatomic) NSNumber* baseline10Bcws;

@property(nonatomic) NSNumber* baseline10Bcwp;

@property(nonatomic) NSArray<ASPExtendedAttribute>* extendedAttributes;

@property(nonatomic) NSArray<ASPOutlineCode>* outlineCodes;

@end
