#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"


@protocol ASPTaskLink
@end

@interface ASPTaskLink : ASPObject


@property(nonatomic) ASPLink* link;

@property(nonatomic) NSNumber* index;

@property(nonatomic) NSNumber* predecessorUid;

@property(nonatomic) NSNumber* successorUid;

@property(nonatomic) NSString* linkType;

@property(nonatomic) NSNumber* lag;

@property(nonatomic) NSString* lagFormat;

@end
