#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"
#import "ASPTaskItem.h"


@protocol ASPTaskItems
@end

@interface ASPTaskItems : ASPObject


@property(nonatomic) NSArray<ASPTaskItem>* taskItem;

@property(nonatomic) ASPLink* link;

@end
