#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPWBSCodeMask
@end

@interface ASPWBSCodeMask : ASPObject


@property(nonatomic) NSNumber* level;

@property(nonatomic) NSString* length;

@property(nonatomic) NSString* sequence;

@property(nonatomic) NSString* separator;

@end
