<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class AssignmentItem {
	static $swaggerTypes = array(
		'Link' => 'Link',
		'Uid' => 'int',
		'TaskUid' => 'int',
		'ResourceUid' => 'int'

	);

	public $Link; // Link
	public $Uid; // int
	public $TaskUid; // int
	public $ResourceUid; // int
	}

