<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class AssignmentsResponse {
	static $swaggerTypes = array(
		'Assignments' => 'ResourceAssignments',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Assignments; // ResourceAssignments
	public $Code; // string
	public $Status; // string
	}

