<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CalendarExceptionsResponse {
	static $swaggerTypes = array(
		'CalendarExceptions' => 'array[CalendarException]',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $CalendarExceptions; // array[CalendarException]
	public $Code; // string
	public $Status; // string
	}

