<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CalendarItemsResponse {
	static $swaggerTypes = array(
		'Items' => 'CalendarItems',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Items; // CalendarItems
	public $Code; // string
	public $Status; // string
	}

