<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Calendar {
	static $swaggerTypes = array(
		'Name' => 'string',
		'Uid' => 'int',
		'Days' => 'array[WeekDay]',
		'Exceptions' => 'array[CalendarException]',
		'IsBaseCalendar' => 'bool',
		'IsBaselineCalendar' => 'bool'

	);

	public $Name; // string
	public $Uid; // int
	public $Days; // array[WeekDay]
	public $Exceptions; // array[CalendarException]
	public $IsBaseCalendar; // bool
	public $IsBaselineCalendar; // bool
	}

