<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CalendarException {
	static $swaggerTypes = array(
		'EnteredByOccurrences' => 'bool',
		'FromDate' => 'DateTime',
		'ToDate' => 'DateTime',
		'Occurrences' => 'int',
		'Name' => 'string',
		'Type' => 'CalendarExceptionType',
		'Period' => 'int',
		'DaysOfWeek' => 'array[DayType]',
		'MonthItem' => 'MonthItemType',
		'MonthPosition' => 'MonthPosition',
		'Month' => 'Month',
		'MonthDay' => 'int',
		'DayWorking' => 'bool',
		'WorkingTimes' => 'array[WorkingTime]'

	);

	public $EnteredByOccurrences; // bool
	public $FromDate; // DateTime
	public $ToDate; // DateTime
	public $Occurrences; // int
	public $Name; // string
	public $Type; // CalendarExceptionType
	public $Period; // int
	public $DaysOfWeek; // array[DayType]
	public $MonthItem; // MonthItemType
	public $MonthPosition; // MonthPosition
	public $Month; // Month
	public $MonthDay; // int
	public $DayWorking; // bool
	public $WorkingTimes; // array[WorkingTime]
	}

