<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ExtendedAttributeResponse {
	static $swaggerTypes = array(
		'ExtendedAttribute' => 'ExtendedAttributeDefinition',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $ExtendedAttribute; // ExtendedAttributeDefinition
	public $Code; // string
	public $Status; // string
	}

