<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ExtendedAttributeItem {
	static $swaggerTypes = array(
		'Link' => 'Link',
		'Index' => 'int',
		'FieldName' => 'string'

	);

	public $Link; // Link
	public $Index; // int
	public $FieldName; // string
	}

