<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class OutlineCodeDefinition {
	static $swaggerTypes = array(
		'Guid' => 'string',
		'FieldId' => 'string',
		'FieldName' => 'string',
		'Alias' => 'string',
		'PhoneticAlias' => 'string',
		'Values' => 'array[OutlineValue]',
		'Enterprise' => 'bool',
		'EnterpriseOutlineCodeAlias' => 'int',
		'ResourceSubstitutionEnabled' => 'bool',
		'LeafOnly' => 'bool',
		'AllLevelsRequired' => 'bool',
		'OnlyTableValuesAllowed' => 'bool',
		'Masks' => 'array[OutlineMask]',
		'ShowIndent' => 'bool'

	);

	public $Guid; // string
	public $FieldId; // string
	public $FieldName; // string
	public $Alias; // string
	public $PhoneticAlias; // string
	public $Values; // array[OutlineValue]
	public $Enterprise; // bool
	public $EnterpriseOutlineCodeAlias; // int
	public $ResourceSubstitutionEnabled; // bool
	public $LeafOnly; // bool
	public $AllLevelsRequired; // bool
	public $OnlyTableValuesAllowed; // bool
	public $Masks; // array[OutlineMask]
	public $ShowIndent; // bool
	}

