<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class OutlineValue {
	static $swaggerTypes = array(
		'ValueId' => 'int',
		'FieldGuid' => 'string',
		'Type' => 'OutlineValueType',
		'ParentValueId' => 'int',
		'Value' => 'string',
		'Description' => 'string',
		'IsCollapsed' => 'bool'

	);

	public $ValueId; // int
	public $FieldGuid; // string
	public $Type; // OutlineValueType
	public $ParentValueId; // int
	public $Value; // string
	public $Description; // string
	public $IsCollapsed; // bool
	}

