<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class OutlineCode {
	static $swaggerTypes = array(
		'FieldId' => 'string',
		'ValueId' => 'int',
		'ValueGuid' => 'string'

	);

	public $FieldId; // string
	public $ValueId; // int
	public $ValueGuid; // string
	}

