<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class OutlineCodeResponse {
	static $swaggerTypes = array(
		'OutlineCode' => 'OutlineCodeDefinition',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $OutlineCode; // OutlineCodeDefinition
	public $Code; // string
	public $Status; // string
	}

