<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Resource {
	static $swaggerTypes = array(
		'Name' => 'string',
		'Uid' => 'int',
		'Id' => 'int',
		'Type' => 'ResourceType',
		'IsNull' => 'bool',
		'Initials' => 'string',
		'Phonetics' => 'string',
		'NtAccount' => 'string',
		'MaterialLabel' => 'string',
		'Code' => 'string',
		'Group' => 'string',
		'EmailAddress' => 'string',
		'Hyperlink' => 'string',
		'HyperlinkAddress' => 'string',
		'HyperlinkSubAddress' => 'string',
		'MaxUnits' => 'float',
		'PeakUnits' => 'float',
		'OverAllocated' => 'bool',
		'AvailableFrom' => 'DateTime',
		'AvailableTo' => 'DateTime',
		'Start' => 'DateTime',
		'Finish' => 'DateTime',
		'CanLevel' => 'bool',
		'AccrueAt' => 'CostAccrualType',
		'Work' => 'string',
		'WorkString' => 'string',
		'RegularWork' => 'string',
		'RegularWorkString' => 'string',
		'OvertimeWork' => 'string',
		'OvertimeWorkString' => 'string',
		'ActualWork' => 'string',
		'ActualWorkString' => 'string',
		'RemainingWork' => 'string',
		'RemainingWorkString' => 'string',
		'ActualOvertimeWork' => 'string',
		'ActualOvertimeWorkString' => 'string',
		'RemainingOvertimeWork' => 'string',
		'RemainingOvertimeWorkString' => 'string',
		'PercentWorkComplete' => 'int',
		'StandardRate' => 'float',
		'StandardRateFormat' => 'RateFormatType',
		'Cost' => 'float',
		'OvertimeRateFormat' => 'RateFormatType',
		'OvertimeCost' => 'float',
		'CostPerUse' => 'float',
		'ActualCost' => 'float',
		'ActualOvertimeCost' => 'float',
		'RemainingCost' => 'float',
		'RemainingOvertimeCost' => 'float',
		'WorkVariance' => 'float',
		'CostVariance' => 'float',
		'Sv' => 'float',
		'Cv' => 'float',
		'Acwp' => 'float',
		'CalendarUid' => 'int',
		'NotesText' => 'string',
		'Bcws' => 'float',
		'Bcwp' => 'float',
		'IsGeneric' => 'bool',
		'IsInactive' => 'bool',
		'IsEnterprise' => 'bool',
		'BookingType' => 'BookingType',
		'ActualWorkProtected' => 'string',
		'ActualWorkProtectedString' => 'string',
		'ActualOvertimeWorkProtected' => 'string',
		'ActualOvertimeWorkProtectedString' => 'string',
		'ActiveDirectoryGuid' => 'string',
		'CreationDate' => 'DateTime',
		'CostCenter' => 'string',
		'IsCostResource' => 'bool',
		'TeamAssignmentPool' => 'bool',
		'AssignmentOwner' => 'string',
		'AssignmentOwnerGuid' => 'string',
		'IsBudget' => 'bool',
		'BudgetWork' => 'string',
		'BudgetWorkString' => 'string',
		'BudgetCost' => 'float',
		'OvertimeRate' => 'float',
		'BaselineWork' => 'string',
		'BaselineWorkString' => 'string',
		'BaselineCost' => 'float',
		'BaselineBcws' => 'float',
		'BaselineBcwp' => 'float',
		'Baseline1Work' => 'string',
		'Baseline1WorkString' => 'string',
		'Baseline1Cost' => 'float',
		'Baseline1Bcws' => 'float',
		'Baseline1Bcwp' => 'float',
		'Baseline2Work' => 'string',
		'Baseline2WorkString' => 'string',
		'Baseline2Cost' => 'float',
		'Baseline2Bcws' => 'float',
		'Baseline2Bcwp' => 'float',
		'Baseline3Work' => 'string',
		'Baseline3WorkString' => 'string',
		'Baseline3Cost' => 'float',
		'Baseline3Bcws' => 'float',
		'Baseline3Bcwp' => 'float',
		'Baseline4Work' => 'string',
		'Baseline4WorkString' => 'string',
		'Baseline4Cost' => 'float',
		'Baseline4Bcws' => 'float',
		'Baseline4Bcwp' => 'float',
		'Baseline5Work' => 'string',
		'Baseline5WorkString' => 'string',
		'Baseline5Cost' => 'float',
		'Baseline5Bcws' => 'float',
		'Baseline5Bcwp' => 'float',
		'Baseline6Work' => 'string',
		'Baseline6WorkString' => 'string',
		'Baseline6Cost' => 'float',
		'Baseline6Bcws' => 'float',
		'Baseline6Bcwp' => 'float',
		'Baseline7Work' => 'string',
		'Baseline7WorkString' => 'string',
		'Baseline7Cost' => 'float',
		'Baseline7Bcws' => 'float',
		'Baseline7Bcwp' => 'float',
		'Baseline8Work' => 'string',
		'Baseline8WorkString' => 'string',
		'Baseline8Cost' => 'float',
		'Baseline8Bcws' => 'float',
		'Baseline8Bcwp' => 'float',
		'Baseline9Work' => 'string',
		'Baseline9WorkString' => 'string',
		'Baseline9Cost' => 'float',
		'Baseline9Bcws' => 'float',
		'Baseline9Bcwp' => 'float',
		'Baseline10Work' => 'string',
		'Baseline10WorkString' => 'string',
		'Baseline10Cost' => 'float',
		'Baseline10Bcws' => 'float',
		'Baseline10Bcwp' => 'float',
		'ExtendedAttributes' => 'array[ExtendedAttribute]',
		'OutlineCodes' => 'array[OutlineCode]'

	);

	public $Name; // string
	public $Uid; // int
	public $Id; // int
	public $Type; // ResourceType
	public $IsNull; // bool
	public $Initials; // string
	public $Phonetics; // string
	public $NtAccount; // string
	public $MaterialLabel; // string
	public $Code; // string
	public $Group; // string
	public $EmailAddress; // string
	public $Hyperlink; // string
	public $HyperlinkAddress; // string
	public $HyperlinkSubAddress; // string
	public $MaxUnits; // float
	public $PeakUnits; // float
	public $OverAllocated; // bool
	public $AvailableFrom; // DateTime
	public $AvailableTo; // DateTime
	public $Start; // DateTime
	public $Finish; // DateTime
	public $CanLevel; // bool
	public $AccrueAt; // CostAccrualType
	public $Work; // string
	public $WorkString; // string
	public $RegularWork; // string
	public $RegularWorkString; // string
	public $OvertimeWork; // string
	public $OvertimeWorkString; // string
	public $ActualWork; // string
	public $ActualWorkString; // string
	public $RemainingWork; // string
	public $RemainingWorkString; // string
	public $ActualOvertimeWork; // string
	public $ActualOvertimeWorkString; // string
	public $RemainingOvertimeWork; // string
	public $RemainingOvertimeWorkString; // string
	public $PercentWorkComplete; // int
	public $StandardRate; // float
	public $StandardRateFormat; // RateFormatType
	public $Cost; // float
	public $OvertimeRateFormat; // RateFormatType
	public $OvertimeCost; // float
	public $CostPerUse; // float
	public $ActualCost; // float
	public $ActualOvertimeCost; // float
	public $RemainingCost; // float
	public $RemainingOvertimeCost; // float
	public $WorkVariance; // float
	public $CostVariance; // float
	public $Sv; // float
	public $Cv; // float
	public $Acwp; // float
	public $CalendarUid; // int
	public $NotesText; // string
	public $Bcws; // float
	public $Bcwp; // float
	public $IsGeneric; // bool
	public $IsInactive; // bool
	public $IsEnterprise; // bool
	public $BookingType; // BookingType
	public $ActualWorkProtected; // string
	public $ActualWorkProtectedString; // string
	public $ActualOvertimeWorkProtected; // string
	public $ActualOvertimeWorkProtectedString; // string
	public $ActiveDirectoryGuid; // string
	public $CreationDate; // DateTime
	public $CostCenter; // string
	public $IsCostResource; // bool
	public $TeamAssignmentPool; // bool
	public $AssignmentOwner; // string
	public $AssignmentOwnerGuid; // string
	public $IsBudget; // bool
	public $BudgetWork; // string
	public $BudgetWorkString; // string
	public $BudgetCost; // float
	public $OvertimeRate; // float
	public $BaselineWork; // string
	public $BaselineWorkString; // string
	public $BaselineCost; // float
	public $BaselineBcws; // float
	public $BaselineBcwp; // float
	public $Baseline1Work; // string
	public $Baseline1WorkString; // string
	public $Baseline1Cost; // float
	public $Baseline1Bcws; // float
	public $Baseline1Bcwp; // float
	public $Baseline2Work; // string
	public $Baseline2WorkString; // string
	public $Baseline2Cost; // float
	public $Baseline2Bcws; // float
	public $Baseline2Bcwp; // float
	public $Baseline3Work; // string
	public $Baseline3WorkString; // string
	public $Baseline3Cost; // float
	public $Baseline3Bcws; // float
	public $Baseline3Bcwp; // float
	public $Baseline4Work; // string
	public $Baseline4WorkString; // string
	public $Baseline4Cost; // float
	public $Baseline4Bcws; // float
	public $Baseline4Bcwp; // float
	public $Baseline5Work; // string
	public $Baseline5WorkString; // string
	public $Baseline5Cost; // float
	public $Baseline5Bcws; // float
	public $Baseline5Bcwp; // float
	public $Baseline6Work; // string
	public $Baseline6WorkString; // string
	public $Baseline6Cost; // float
	public $Baseline6Bcws; // float
	public $Baseline6Bcwp; // float
	public $Baseline7Work; // string
	public $Baseline7WorkString; // string
	public $Baseline7Cost; // float
	public $Baseline7Bcws; // float
	public $Baseline7Bcwp; // float
	public $Baseline8Work; // string
	public $Baseline8WorkString; // string
	public $Baseline8Cost; // float
	public $Baseline8Bcws; // float
	public $Baseline8Bcwp; // float
	public $Baseline9Work; // string
	public $Baseline9WorkString; // string
	public $Baseline9Cost; // float
	public $Baseline9Bcws; // float
	public $Baseline9Bcwp; // float
	public $Baseline10Work; // string
	public $Baseline10WorkString; // string
	public $Baseline10Cost; // float
	public $Baseline10Bcws; // float
	public $Baseline10Bcwp; // float
	public $ExtendedAttributes; // array[ExtendedAttribute]
	public $OutlineCodes; // array[OutlineCode]
	}

