<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ResourceResponse {
	static $swaggerTypes = array(
		'Resource' => 'Resource',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Resource; // Resource
	public $Code; // string
	public $Status; // string
	}

