<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ResourceItemResponse {
	static $swaggerTypes = array(
		'ResourceItem' => 'ResourceItem',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $ResourceItem; // ResourceItem
	public $Code; // string
	public $Status; // string
	}

