<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ResourceItemsResponse {
	static $swaggerTypes = array(
		'Items' => 'ResourceItems',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Items; // ResourceItems
	public $Code; // string
	public $Status; // string
	}

