<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ResourceItems {
	static $swaggerTypes = array(
		'List' => 'array[ResourceItem]',
		'link' => 'Link'

	);

	public $List; // array[ResourceItem]
	public $link; // Link
	}

