<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TaskItem {
	static $swaggerTypes = array(
		'Link' => 'Link',
		'Uid' => 'int',
		'Id' => 'int',
		'Name' => 'string',
		'Start' => 'DateTime',
		'Finish' => 'DateTime',
		'Duration' => 'string',
		'DurationString' => 'string'

	);

	public $Link; // Link
	public $Uid; // int
	public $Id; // int
	public $Name; // string
	public $Start; // DateTime
	public $Finish; // DateTime
	public $Duration; // string
	public $DurationString; // string
	}

