<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TaskLinksResponse {
	static $swaggerTypes = array(
		'TaskLinks' => 'array[TaskLink]',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $TaskLinks; // array[TaskLink]
	public $Code; // string
	public $Status; // string
	}

