<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TaskResponse {
	static $swaggerTypes = array(
		'Task' => 'Task',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Task; // Task
	public $Code; // string
	public $Status; // string
	}

