<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class WeekDay {
	static $swaggerTypes = array(
		'DayType' => 'DayType',
		'DayWorking' => 'bool',
		'FromDate' => 'DateTime',
		'ToDate' => 'DateTime',
		'WorkingTimes' => 'array[WorkingTime]'

	);

	public $DayType; // DayType
	public $DayWorking; // bool
	public $FromDate; // DateTime
	public $ToDate; // DateTime
	public $WorkingTimes; // array[WorkingTime]
	}

