<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class WorkingTime {
	static $swaggerTypes = array(
		'FromTime' => 'DateTime',
		'ToTime' => 'DateTime'

	);

	public $FromTime; // DateTime
	public $ToTime; // DateTime
	}

