<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class AssignmentItemResponse {
	static $swaggerTypes = array(
		'AssignmentItem' => 'AssignmentItem',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $AssignmentItem; // AssignmentItem
	public $Code; // string
	public $Status; // string
	}

