<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class AssignmentResponse {
	static $swaggerTypes = array(
		'Assignment' => 'ResourceAssignment',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Assignment; // ResourceAssignment
	public $Code; // string
	public $Status; // string
	}

