<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CalendarItemResponse {
	static $swaggerTypes = array(
		'CalendarItem' => 'CalendarItem',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $CalendarItem; // CalendarItem
	public $Code; // string
	public $Status; // string
	}

