<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CalendarItem {
	static $swaggerTypes = array(
		'Link' => 'Link',
		'Uid' => 'int',
		'Name' => 'string'

	);

	public $Link; // Link
	public $Uid; // int
	public $Name; // string
	}

