<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CalendarResponse {
	static $swaggerTypes = array(
		'Calendar' => 'Calendar',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Calendar; // Calendar
	public $Code; // string
	public $Status; // string
	}

