<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class DocumentPropertiesResponse {
	static $swaggerTypes = array(
		'Properties' => 'DocumentProperties',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Properties; // DocumentProperties
	public $Code; // string
	public $Status; // string
	}

