<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ExtendedAttributeDefinition {
	static $swaggerTypes = array(
		'FieldId' => 'string',
		'FieldName' => 'string',
		'CfType' => 'CustomFieldType',
		'Guid' => 'string',
		'ElementType' => 'ElementType',
		'MaxMultiValues' => 'int',
		'UserDef' => 'bool',
		'Alias' => 'string',
		'SecondaryPid' => 'string',
		'AutoRollDown' => 'bool',
		'DefaultGuid' => 'string',
		'LookupUid' => 'string',
		'PhoneticsAlias' => 'string',
		'RollupType' => 'RollupType',
		'CalculationType' => 'CalculationType',
		'Formula' => 'string',
		'RestrictValues' => 'bool',
		'ValuelistSortOrder' => 'int',
		'AppendNewValues' => 'bool',
		'Default' => 'string',
		'ValueList' => 'array[Value]',
		'SecondaryGuid' => 'string'

	);

	public $FieldId; // string
	public $FieldName; // string
	public $CfType; // CustomFieldType
	public $Guid; // string
	public $ElementType; // ElementType
	public $MaxMultiValues; // int
	public $UserDef; // bool
	public $Alias; // string
	public $SecondaryPid; // string
	public $AutoRollDown; // bool
	public $DefaultGuid; // string
	public $LookupUid; // string
	public $PhoneticsAlias; // string
	public $RollupType; // RollupType
	public $CalculationType; // CalculationType
	public $Formula; // string
	public $RestrictValues; // bool
	public $ValuelistSortOrder; // int
	public $AppendNewValues; // bool
	public $Default; // string
	public $ValueList; // array[Value]
	public $SecondaryGuid; // string
	}

