<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ExtendedAttribute {
	static $swaggerTypes = array(
		'FieldId' => 'string',
		'Value' => 'string',
		'ValueGuid' => 'string',
		'DurationFormat' => 'TimeUnitType'

	);

	public $FieldId; // string
	public $Value; // string
	public $ValueGuid; // string
	public $DurationFormat; // TimeUnitType
	}

