<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class OutlineMask {
	static $swaggerTypes = array(
		'Level' => 'int',
		'Type' => 'MaskType',
		'Length' => 'int',
		'Separator' => 'string'

	);

	public $Level; // int
	public $Type; // MaskType
	public $Length; // int
	public $Separator; // string
	}

