<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ResourceAssignment {
	static $swaggerTypes = array(
		'TaskUid' => 'int',
		'ResourceUid' => 'int',
		'Uid' => 'int',
		'PercentWorkComplete' => 'int',
		'ActualCost' => 'float',
		'ActualFinish' => 'DateTime',
		'ActualOvertimeCost' => 'float',
		'ActualOvertimeWork' => 'string',
		'ActualOvertimeWorkString' => 'string',
		'ActualStart' => 'DateTime',
		'ActualWork' => 'string',
		'ActualWorkString' => 'string',
		'Acwp' => 'float',
		'Confirmed' => 'bool',
		'Cost' => 'float',
		'CostRateTableType' => 'RateType',
		'CostVariance' => 'float',
		'Cv' => 'float',
		'Delay' => 'int',
		'Finish' => 'DateTime',
		'FinishVariance' => 'int',
		'Hyperlink' => 'string',
		'HyperlinkAddress' => 'string',
		'HyperlinkSubAddress' => 'string',
		'WorkVariance' => 'float',
		'HasFixedRateUnits' => 'bool',
		'FixedMaterial' => 'bool',
		'LevelingDelay' => 'int',
		'LevelingDelayFormat' => 'TimeUnitType',
		'LinkedFields' => 'bool',
		'Milestone' => 'bool',
		'Notes' => 'string',
		'Overallocated' => 'bool',
		'OvertimeCost' => 'float',
		'OvertimeWork' => 'string',
		'OvertimeWorkString' => 'string',
		'PeakUnits' => 'float',
		'RegularWork' => 'string',
		'RegularWorkString' => 'string',
		'RemainingCost' => 'float',
		'RemainingOvertimeCost' => 'float',
		'RemainingOvertimeWork' => 'string',
		'RemainingOvertimeWorkString' => 'string',
		'RemainingWork' => 'string',
		'RemainingWorkString' => 'string',
		'ResponsePending' => 'bool',
		'Start' => 'DateTime',
		'Stop' => 'DateTime',
		'Resume' => 'DateTime',
		'StartVariance' => 'int',
		'Summary' => 'bool',
		'Sv' => 'float',
		'Units' => 'float',
		'UpdateNeeded' => 'bool',
		'Vac' => 'float',
		'Work' => 'string',
		'WorkString' => 'string',
		'WorkContour' => 'WorkContourType',
		'Bcws' => 'float',
		'Bcwp' => 'float',
		'BookingType' => 'BookingType',
		'ActualWorkProtected' => 'string',
		'ActualWorkProtectedString' => 'string',
		'ActualOvertimeWorkProtected' => 'string',
		'ActualOvertimeWorkProtectedString' => 'string',
		'CreationDate' => 'DateTime',
		'AssnOwner' => 'string',
		'AssnOwnerGuid' => 'string',
		'BudgetCost' => 'float',
		'BudgetWork' => 'string',
		'BudgetWorkString' => 'string',
		'RateScale' => 'int',
		'BaselineStart' => 'DateTime',
		'BaselineFinish' => 'DateTime',
		'BaselineWork' => 'string',
		'BaselineWorkString' => 'string',
		'BaselineCost' => 'float',
		'BaselineBcws' => 'float',
		'BaselineBcwp' => 'float',
		'Baseline1Start' => 'DateTime',
		'Baseline1Finish' => 'DateTime',
		'Baseline1Work' => 'string',
		'Baseline1WorkString' => 'string',
		'Baseline1Cost' => 'float',
		'Baseline1Bcws' => 'float',
		'Baseline1Bcwp' => 'float',
		'Baseline2Start' => 'DateTime',
		'Baseline2Finish' => 'DateTime',
		'Baseline2Work' => 'string',
		'Baseline2WorkString' => 'string',
		'Baseline2Cost' => 'float',
		'Baseline2Bcws' => 'float',
		'Baseline2Bcwp' => 'float',
		'Baseline3Start' => 'DateTime',
		'Baseline3Finish' => 'DateTime',
		'Baseline3Work' => 'string',
		'Baseline3WorkString' => 'string',
		'Baseline3Cost' => 'float',
		'Baseline3Bcws' => 'float',
		'Baseline3Bcwp' => 'float',
		'Baseline4Start' => 'DateTime',
		'Baseline4Finish' => 'DateTime',
		'Baseline4Work' => 'string',
		'Baseline4WorkString' => 'string',
		'Baseline4Cost' => 'float',
		'Baseline4Bcws' => 'float',
		'Baseline4Bcwp' => 'float',
		'Baseline5Start' => 'DateTime',
		'Baseline5Finish' => 'DateTime',
		'Baseline5Work' => 'string',
		'Baseline5WorkString' => 'string',
		'Baseline5Cost' => 'float',
		'Baseline5Bcws' => 'float',
		'Baseline5Bcwp' => 'float',
		'Baseline6Start' => 'DateTime',
		'Baseline6Finish' => 'DateTime',
		'Baseline6Work' => 'string',
		'Baseline6WorkString' => 'string',
		'Baseline6Cost' => 'float',
		'Baseline6Bcws' => 'float',
		'Baseline6Bcwp' => 'float',
		'Baseline7Start' => 'DateTime',
		'Baseline7Finish' => 'DateTime',
		'Baseline7Work' => 'string',
		'Baseline7WorkString' => 'string',
		'Baseline7Cost' => 'float',
		'Baseline7Bcws' => 'float',
		'Baseline7Bcwp' => 'float',
		'Baseline8Start' => 'DateTime',
		'Baseline8Finish' => 'DateTime',
		'Baseline8Work' => 'string',
		'Baseline8WorkString' => 'string',
		'Baseline8Cost' => 'float',
		'Baseline8Bcws' => 'float',
		'Baseline8Bcwp' => 'float',
		'Baseline9Start' => 'DateTime',
		'Baseline9Finish' => 'DateTime',
		'Baseline9Work' => 'string',
		'Baseline9WorkString' => 'string',
		'Baseline9Cost' => 'float',
		'Baseline9Bcws' => 'float',
		'Baseline9Bcwp' => 'float',
		'Baseline10Start' => 'DateTime',
		'Baseline10Finish' => 'DateTime',
		'Baseline10Work' => 'string',
		'Baseline10WorkString' => 'string',
		'Baseline10Cost' => 'float',
		'Baseline10Bcws' => 'float',
		'Baseline10Bcwp' => 'float',
		'ExtendedAttributes' => 'array[ExtendedAttribute]'

	);

	public $TaskUid; // int
	public $ResourceUid; // int
	public $Uid; // int
	public $PercentWorkComplete; // int
	public $ActualCost; // float
	public $ActualFinish; // DateTime
	public $ActualOvertimeCost; // float
	public $ActualOvertimeWork; // string
	public $ActualOvertimeWorkString; // string
	public $ActualStart; // DateTime
	public $ActualWork; // string
	public $ActualWorkString; // string
	public $Acwp; // float
	public $Confirmed; // bool
	public $Cost; // float
	public $CostRateTableType; // RateType
	public $CostVariance; // float
	public $Cv; // float
	public $Delay; // int
	public $Finish; // DateTime
	public $FinishVariance; // int
	public $Hyperlink; // string
	public $HyperlinkAddress; // string
	public $HyperlinkSubAddress; // string
	public $WorkVariance; // float
	public $HasFixedRateUnits; // bool
	public $FixedMaterial; // bool
	public $LevelingDelay; // int
	public $LevelingDelayFormat; // TimeUnitType
	public $LinkedFields; // bool
	public $Milestone; // bool
	public $Notes; // string
	public $Overallocated; // bool
	public $OvertimeCost; // float
	public $OvertimeWork; // string
	public $OvertimeWorkString; // string
	public $PeakUnits; // float
	public $RegularWork; // string
	public $RegularWorkString; // string
	public $RemainingCost; // float
	public $RemainingOvertimeCost; // float
	public $RemainingOvertimeWork; // string
	public $RemainingOvertimeWorkString; // string
	public $RemainingWork; // string
	public $RemainingWorkString; // string
	public $ResponsePending; // bool
	public $Start; // DateTime
	public $Stop; // DateTime
	public $Resume; // DateTime
	public $StartVariance; // int
	public $Summary; // bool
	public $Sv; // float
	public $Units; // float
	public $UpdateNeeded; // bool
	public $Vac; // float
	public $Work; // string
	public $WorkString; // string
	public $WorkContour; // WorkContourType
	public $Bcws; // float
	public $Bcwp; // float
	public $BookingType; // BookingType
	public $ActualWorkProtected; // string
	public $ActualWorkProtectedString; // string
	public $ActualOvertimeWorkProtected; // string
	public $ActualOvertimeWorkProtectedString; // string
	public $CreationDate; // DateTime
	public $AssnOwner; // string
	public $AssnOwnerGuid; // string
	public $BudgetCost; // float
	public $BudgetWork; // string
	public $BudgetWorkString; // string
	public $RateScale; // int
	public $BaselineStart; // DateTime
	public $BaselineFinish; // DateTime
	public $BaselineWork; // string
	public $BaselineWorkString; // string
	public $BaselineCost; // float
	public $BaselineBcws; // float
	public $BaselineBcwp; // float
	public $Baseline1Start; // DateTime
	public $Baseline1Finish; // DateTime
	public $Baseline1Work; // string
	public $Baseline1WorkString; // string
	public $Baseline1Cost; // float
	public $Baseline1Bcws; // float
	public $Baseline1Bcwp; // float
	public $Baseline2Start; // DateTime
	public $Baseline2Finish; // DateTime
	public $Baseline2Work; // string
	public $Baseline2WorkString; // string
	public $Baseline2Cost; // float
	public $Baseline2Bcws; // float
	public $Baseline2Bcwp; // float
	public $Baseline3Start; // DateTime
	public $Baseline3Finish; // DateTime
	public $Baseline3Work; // string
	public $Baseline3WorkString; // string
	public $Baseline3Cost; // float
	public $Baseline3Bcws; // float
	public $Baseline3Bcwp; // float
	public $Baseline4Start; // DateTime
	public $Baseline4Finish; // DateTime
	public $Baseline4Work; // string
	public $Baseline4WorkString; // string
	public $Baseline4Cost; // float
	public $Baseline4Bcws; // float
	public $Baseline4Bcwp; // float
	public $Baseline5Start; // DateTime
	public $Baseline5Finish; // DateTime
	public $Baseline5Work; // string
	public $Baseline5WorkString; // string
	public $Baseline5Cost; // float
	public $Baseline5Bcws; // float
	public $Baseline5Bcwp; // float
	public $Baseline6Start; // DateTime
	public $Baseline6Finish; // DateTime
	public $Baseline6Work; // string
	public $Baseline6WorkString; // string
	public $Baseline6Cost; // float
	public $Baseline6Bcws; // float
	public $Baseline6Bcwp; // float
	public $Baseline7Start; // DateTime
	public $Baseline7Finish; // DateTime
	public $Baseline7Work; // string
	public $Baseline7WorkString; // string
	public $Baseline7Cost; // float
	public $Baseline7Bcws; // float
	public $Baseline7Bcwp; // float
	public $Baseline8Start; // DateTime
	public $Baseline8Finish; // DateTime
	public $Baseline8Work; // string
	public $Baseline8WorkString; // string
	public $Baseline8Cost; // float
	public $Baseline8Bcws; // float
	public $Baseline8Bcwp; // float
	public $Baseline9Start; // DateTime
	public $Baseline9Finish; // DateTime
	public $Baseline9Work; // string
	public $Baseline9WorkString; // string
	public $Baseline9Cost; // float
	public $Baseline9Bcws; // float
	public $Baseline9Bcwp; // float
	public $Baseline10Start; // DateTime
	public $Baseline10Finish; // DateTime
	public $Baseline10Work; // string
	public $Baseline10WorkString; // string
	public $Baseline10Cost; // float
	public $Baseline10Bcws; // float
	public $Baseline10Bcwp; // float
	public $ExtendedAttributes; // array[ExtendedAttribute]
	}

