<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TaskLinkResponse {
	static $swaggerTypes = array(
		'TaskLink' => 'TaskLink',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $TaskLink; // TaskLink
	public $Code; // string
	public $Status; // string
	}

