<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TaskLink {
	static $swaggerTypes = array(
		'Link' => 'Link',
		'Index' => 'int',
		'PredecessorUid' => 'int',
		'SuccessorUid' => 'int',
		'LinkType' => 'TaskLinkType',
		'Lag' => 'int',
		'LagFormat' => 'TimeUnitType'

	);

	public $Link; // Link
	public $Index; // int
	public $PredecessorUid; // int
	public $SuccessorUid; // int
	public $LinkType; // TaskLinkType
	public $Lag; // int
	public $LagFormat; // TimeUnitType
	}

