<?php
namespace Aspose\Tasks\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Value {
	static $swaggerTypes = array(
		'Id' => 'int',
		'Val' => 'string',
		'Description' => 'string',
		'Phonetic' => 'string'

	);

	public $Id; // int
	public $Val; // string
	public $Description; // string
	public $Phonetic; // string
	}

