#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"
#import "ASPAssignmentItem.h"


@protocol ASPAssignmentItems
@end

@interface ASPAssignmentItems : ASPObject


@property(nonatomic) NSArray<ASPAssignmentItem>* assignmentItem;

@property(nonatomic) ASPLink* link;

@end
