#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPCalendar.h"
#import "ASPWeekDay.h"
#import "ASPCalendarException.h"


@protocol ASPCalendar
@end

@interface ASPCalendar : ASPObject


@property(nonatomic) NSString* name;

@property(nonatomic) NSNumber* uid;

@property(nonatomic) NSArray<ASPWeekDay>* days;

@property(nonatomic) NSArray<ASPCalendarException>* exceptions;

@property(nonatomic) NSNumber* isBaseCalendar;

@property(nonatomic) ASPCalendar* baseCalendar;

@property(nonatomic) NSNumber* isBaselineCalendar;

@end
