#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPExtendedAttribute
@end

@interface ASPExtendedAttribute : ASPObject


@property(nonatomic) NSString* fieldId;

@property(nonatomic) NSString* value;

@property(nonatomic) NSString* valueGuid;

@property(nonatomic) NSString* durationFormat;

@end
