#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPOutlineValue
@end

@interface ASPOutlineValue : ASPObject


@property(nonatomic) NSNumber* valueId;

@property(nonatomic) NSString* fieldGuid;

@property(nonatomic) NSString* type;

@property(nonatomic) NSNumber* parentValueId;

@property(nonatomic) NSString* value;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSNumber* isCollapsed;

@end
