#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"


@protocol ASPOutlineCodeItem
@end

@interface ASPOutlineCodeItem : ASPObject


@property(nonatomic) ASPLink* link;

@property(nonatomic) NSNumber* index;

@end
