#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPResourceAssignment.h"
#import "ASPLink.h"


@protocol ASPResourceAssignments
@end

@interface ASPResourceAssignments : ASPObject


@property(nonatomic) NSArray<ASPResourceAssignment>* list;

@property(nonatomic) ASPLink* link;

@end
