#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPRecurringInfo
@end

@interface ASPRecurringInfo : ASPObject


@property(nonatomic) NSString* recurrencePattern;

@property(nonatomic) NSDate* startDate;

@property(nonatomic) NSDate* endDate;

@property(nonatomic) NSString* duration;

@property(nonatomic) NSNumber* occurrences;

@property(nonatomic) NSNumber* useEndDate;

@property(nonatomic) NSNumber* dailyRepetitions;

@property(nonatomic) NSNumber* dailyUseWorkdays;

@property(nonatomic) NSNumber* weeklyRepetitions;

@property(nonatomic) NSString* weeklyDays;

@property(nonatomic) NSNumber* monthlyUseOrdinalDay;

@property(nonatomic) NSString* monthlyOrdinalNumber;

@property(nonatomic) NSString* monthlyOrdinalDay;

@property(nonatomic) NSNumber* monthlyOrdinalRepetitions;

@property(nonatomic) NSNumber* monthlyDay;

@property(nonatomic) NSNumber* monthlyRepetitions;

@property(nonatomic) NSNumber* yearlyUseOrdinalDay;

@property(nonatomic) NSDate* yearlyDate;

@property(nonatomic) NSString* yearlyOrdinalNumber;

@property(nonatomic) NSString* yearlyOrdinalDay;

@property(nonatomic) NSString* yearlyOrdinalMonth;

@end
