#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPRecurringInfo.h"


@protocol ASPRecurringInfoResponse
@end

@interface ASPRecurringInfoResponse : ASPObject


@property(nonatomic) ASPRecurringInfo* recurringInfo;

@property(nonatomic) NSString* code;

@property(nonatomic) NSString* status;

@end
