#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPValue
@end

@interface ASPValue : ASPObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* val;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSString* phonetic;

@end
