#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPWorkingTime
@end

@interface ASPWorkingTime : ASPObject


@property(nonatomic) NSDate* fromTime;

@property(nonatomic) NSDate* toTime;

@end
