#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPWBSCodeMask.h"


@protocol ASPWBSDefinition
@end

@interface ASPWBSDefinition : ASPObject


@property(nonatomic) NSString* codePrefix;

@property(nonatomic) NSNumber* generateWBSCode;

@property(nonatomic) NSNumber* verifyUniqueness;

@property(nonatomic) NSArray<ASPWBSCodeMask>* codeMaskCollection;

@end
